version: "3.8"

services:
    oraculo-api:
        build: .
        container_name: oraculo-api
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings_dev
            - SECRET_KEY=changeme
            - GITHUB_API_KEY=changeme
            - LOG_FILE_NAME=oraculo.log
            - LOG_LEVEL=DEBUG
            - DB_DATABASE=oraculo
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=oraculo-db
            - DB_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - ./src:/app
        ports:
            - "8000:8000"
        depends_on:
            - oraculo-db
            - oraculo-redis
    oraculo-jobs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: orauco-jobs
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings_dev
            - SECRET_KEY=changeme
            - GITHUB_API_KEY=changeme
            - LOG_FILE_NAME=oraculo.log
            - LOG_LEVEL=INFO
            - DB_DATABASE=oraculo
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=oraculo-db
            - DB_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6380
        volumes:
            - ./src:/app
        depends_on:
            - oraculo-db
            - oraculo-redis
    oraculo-db:
        image: postgres:13
        container_name: oraculo-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=oraculo
        volumes:
            - db_data:/var/lib/data
        ports:
            - "5432:5432"
    oraculo-redis:
        restart: always
        image: redis:alpine
        container_name: oraculo-redis
        ports:
            - "6380:6380"

volumes:
    db_data:
